mode = "dark"

# Derived from goes-20260905-1803Z.jpg by omarchy-satellite-palette
# ocean=#021124 cloud=#d2d4d6 forest=#3e4c37 sand=#776555 earth=#493315 shoal=#0e5f69

accent = "#60b4be"
selection = "#2b3b50"
muted = "#455568"

background = "#111d2c"
dark_background = "#0a131f"
darker_background = "#060c14"
lighter_background = "#1e2c3e"

foreground = "#d9dbdd"
dark_foreground = "#94999e"
light_foreground = "#c9cccf"
bright_foreground = "#ecedee"

red = "#ce7a64"
yellow = "#cfa681"
orange = "#d49e54"
green = "#88b672"
cyan = "#72b7c0"
blue = "#7599c7"
magenta = "#b390c1"
brown = "#604724"

bright_red = "#de917c"
bright_yellow = "#e0bb99"
bright_green = "#9ccb86"
bright_cyan = "#88cad3"
bright_blue = "#8caed9"
bright_magenta = "#c7a5d5"
